-- Run in Supabase SQL Editor to create the CFT submissions table (v0.1).
-- Separate from rit_submissions / gmt22_submissions. No PHI columns.

CREATE TABLE IF NOT EXISTS cft_submissions (
  id BIGSERIAL PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE,
  anonymous_participant_id TEXT NOT NULL DEFAULT '',
  study_id TEXT NOT NULL DEFAULT '',
  administration_mode TEXT NOT NULL DEFAULT '',
  visual_mode TEXT NOT NULL DEFAULT '',
  task_version TEXT NOT NULL DEFAULT '',
  scoring_version TEXT NOT NULL DEFAULT '',
  study_version TEXT NOT NULL DEFAULT '',
  consent_version TEXT NOT NULL DEFAULT '',
  randomization_seed BIGINT NOT NULL DEFAULT 0,
  start_time TIMESTAMPTZ NULL,
  completion_time TIMESTAMPTZ NULL,
  total_duration_ms BIGINT NULL,
  device_type TEXT NOT NULL DEFAULT '',
  input_method TEXT NOT NULL DEFAULT '',
  practice_repetitions INTEGER NOT NULL DEFAULT 0,
  timing_quality TEXT NOT NULL DEFAULT '',
  completion_status TEXT NOT NULL DEFAULT '',
  provisional_cfs NUMERIC NULL,
  switch_accuracy NUMERIC NULL,
  stay_accuracy NUMERIC NULL,
  switch_cost_rt_ms NUMERIC NULL,
  switch_cost_accuracy NUMERIC NULL,
  perseverative_error_rate NUMERIC NULL,
  rule_maintenance_error_rate NUMERIC NULL,
  cue_processing_error_rate NUMERIC NULL,
  conflict_accuracy NUMERIC NULL,
  omission_error_rate NUMERIC NULL,
  mean_correct_rt_ms NUMERIC NULL,
  median_correct_rt_ms NUMERIC NULL,
  rt_sd_ms NUMERIC NULL,
  rt_cv NUMERIC NULL,
  anticipatory_count INTEGER NOT NULL DEFAULT 0,
  post_error_recovery NUMERIC NULL,
  high_interference_accuracy NUMERIC NULL,
  accuracy_practice NUMERIC NULL,
  mean_rt_practice NUMERIC NULL,
  accuracy_rule_learning NUMERIC NULL,
  mean_rt_rule_learning NUMERIC NULL,
  accuracy_predictable_switch NUMERIC NULL,
  mean_rt_predictable_switch NUMERIC NULL,
  accuracy_cued_switch NUMERIC NULL,
  mean_rt_cued_switch NUMERIC NULL,
  accuracy_interference NUMERIC NULL,
  mean_rt_interference NUMERIC NULL,
  validity_flags TEXT NOT NULL DEFAULT '',
  flag_excessive_omissions BOOLEAN NOT NULL DEFAULT false,
  flag_chance_accuracy BOOLEAN NOT NULL DEFAULT false,
  flag_extremely_rapid BOOLEAN NOT NULL DEFAULT false,
  flag_repeated_anticipatory BOOLEAN NOT NULL DEFAULT false,
  flag_excessive_focus_loss BOOLEAN NOT NULL DEFAULT false,
  flag_incomplete_session BOOLEAN NOT NULL DEFAULT false,
  flag_abnormal_timing BOOLEAN NOT NULL DEFAULT false,
  flag_unsupported_device BOOLEAN NOT NULL DEFAULT false,
  flag_repeated_response_pattern BOOLEAN NOT NULL DEFAULT false,
  flag_practice_failed BOOLEAN NOT NULL DEFAULT false,
  flag_rule_not_understood BOOLEAN NOT NULL DEFAULT false,
  flag_excessive_perseveration BOOLEAN NOT NULL DEFAULT false,
  trials JSONB NOT NULL DEFAULT '[]',
  demographics JSONB NOT NULL DEFAULT '{}',
  examiner_notes TEXT NULL,
  data_retention_policy TEXT NOT NULL DEFAULT '',
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS cft_submissions_study_id_idx ON cft_submissions (study_id);
CREATE INDEX IF NOT EXISTS cft_submissions_task_version_idx ON cft_submissions (task_version);
CREATE INDEX IF NOT EXISTS cft_submissions_visual_mode_idx ON cft_submissions (visual_mode);

ALTER TABLE cft_submissions ENABLE ROW LEVEL SECURITY;
