-- Long-format trial export for CFT (one row per trial).

CREATE OR REPLACE VIEW cft_trials AS
SELECT
  s.id AS submission_id,
  s.session_id,
  s.anonymous_participant_id,
  s.study_id,
  s.visual_mode,
  s.task_version,
  s.scoring_version,
  t.trial_idx,
  (t.trial->>'blockId')::text AS block_id,
  (t.trial->>'blockType')::text AS block_type,
  (t.trial->>'trialNumber')::integer AS trial_number,
  (t.trial->>'stimulusId')::text AS stimulus_id,
  (t.trial->>'rule')::text AS rule,
  (t.trial->>'previousRule')::text AS previous_rule,
  COALESCE((t.trial->>'isSwitch')::boolean, false) AS is_switch,
  (t.trial->>'congruency')::text AS congruency,
  (t.trial->'stimulusProperties'->'features'->>'shape')::text AS shape,
  (t.trial->'stimulusProperties'->'features'->>'pattern')::text AS pattern,
  (t.trial->'stimulusProperties'->'features'->>'number')::text AS number_feature,
  (t.trial->>'expectedResponse')::text AS expected_response,
  (t.trial->>'actualResponse')::text AS actual_response,
  (t.trial->>'accuracy')::integer AS accuracy,
  (t.trial->>'errorType')::text AS error_type,
  (t.trial->>'reactionTimeMs')::numeric AS reaction_time_ms,
  (t.trial->>'stimulusOnsetTs')::numeric AS stimulus_onset_ts,
  (t.trial->>'responseTimestamp')::numeric AS response_timestamp,
  (t.trial->>'interstimulusIntervalMs')::numeric AS interstimulus_interval_ms,
  COALESCE((t.trial->>'anticipatoryResponseFlag')::boolean, false) AS anticipatory_response_flag,
  COALESCE((t.trial->>'omissionFlag')::boolean, false) AS omission_flag,
  COALESCE((t.trial->>'focusLossFlag')::boolean, false) AS focus_loss_flag,
  COALESCE((t.trial->>'timingIrregularityFlag')::boolean, false) AS timing_irregularity_flag,
  COALESCE((t.trial->>'invalidKeyFlag')::boolean, false) AS invalid_key_flag,
  COALESCE((t.trial->>'scored')::boolean, false) AS scored
FROM cft_submissions s,
LATERAL jsonb_array_elements(s.trials) WITH ORDINALITY AS t(trial, trial_idx);
