-- Run in Supabase SQL Editor. Adds span-centered summary columns.
-- Safe to re-run: uses ADD COLUMN IF NOT EXISTS.

ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS baseline_span INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS ignore_span INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS remember_span INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS delay_span INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS interference_cost INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS binding_cost INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gmt22_submissions ADD COLUMN IF NOT EXISTS delay_cost INTEGER NOT NULL DEFAULT 0;
